---
title: "Post Lab Exercises Week 6 NLS"
format: 
  html:
    embed-resources: true
    code-fold: true
    toc: true
execute: 
  echo: true
  warning: false
  message: false
---

## Set up

Create your own quarto document to answer these questions. Attach all necessary packages and load the lizard data from the github data folder. Complete at least the first lizard nls model in lab and show either Casey or Nathan before you leave.


## Purrr Practice

1. What data type do the following functions return?

  + `map()`
  + `map_chr()`
  + `map_dbl()`
  + `map_df()`
  + `map_lgl()`

2. If I have a dataset where I want to iterate over 4 different variables that are changing, which of the following functions would I use?

  a. `map()`
  b. `map2()`
  c. `pmap()`
  d. `mutate()`
  
3. Format the out of order code into the correct order for it to run

```{r, eval=FALSE}
janitor::clean_names() |> 
mutate(reg=map(.x=data, ~lm(life_exp~pop+gdp_per_cap+year,data=.x))) |> 
output <- gapminder |> 
mutate(coeff=map(.x=reg, ~coefficients(.x)))
nest(.by=continent) |> 
```  
  
4. Generate 10 random samples from a normal distribution where the mean and standard deviation increase from 1 to 10 and  to 20. Hint: Make sure the sequences are of the same length by setting the length.out=11 argument in seq()

5. Use purrr to quickly return the class of every column from the `gapminder` dataset as characters

## NLS Practice

Source: Lightfoot, D. and W.G. Whitford. 2020. Lizard pitfall trap data from 11 NPP study locations at the Jornada Basin LTER site, 1989-2006 ver 37. Environmental Data Initiative. https://doi.org/10.6073/pasta/4a6e258fb49c31e222ecbbcfd128967f

For task 2, you will use non linear least squares to estimate parameters of a length to weight model for lizard populations in New Mexico. 

1) Create a dataframe of only the sex, species, snout to vent length, and weight. Exclude juveniles from the analysis. Remove any species that possess less than 6 observations. Finally, make sure you "balance" the data between male and female observations (e.g. make sure all species that are selected have observations of both male and female). Show the list of the species that will be used in the rest of the task (can just print out, no need for a table)

2) Fit a snout length to weight model of the following form to all lizard in your clean dataframe.

\begin{equation}
W=a(SVL)^b
\end{equation}

  a) Weight is given by W, snout to vent length by SVL, and a and b are the parameters that need to be fitted. Which strategy would be best to provide an initial guess? We could go with strategy one and look through the literature, but let’s practice our coding and math skills.
  
  b) Since we know the model is exponential in nature, we could log transform the data. If we do a standard OLS regression on the log transformed data, we can get approximations of the parameters from the regression coefficients
`my_guess_model <- lm(log_weight ~ log_length, data = my_df) `

  c) Using the coefficients function, we can then supply the nls start list with the regression coefficients. You will have to mathematically transform the intercept coefficient to get the guess for parameter a. 
  
3) Present your fitted model on a plot with female and male lizards separated by color. You should include the nls model in `kable` output of the html. 

**The following parts are super-mega optional! It's using purrr to run on all species. If you're craving more continue on. Otherwise you will be asked to do something similar in your homework!**

4) Group by species and sex then nest the data. Use `map()` variants to parameterize length to weight models for every species separated by each sex. Hint: you may need to adjust the controls of the `nls` function

5) Use the models to predict the data. Calculate the RMSE for each model created in part 3. Make at able showing the RMSE for each model.

6) Create a plot grid showing each species and sexes actual weight and the model prediction.

